In [7]:
# INITIALIZING DIFFERENT TYPES OF ARRAYS
# All 0s matrix
import numpy as np
np.zeros((2))

array([0., 0.])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [12]:
np.zeros((3,2,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [13]:
# numpy is very crazy
np.zeros((2,3,3,2,2))

array([[[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]],



       [[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]]])

In [25]:
# All 1s matrix
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [28]:

np.ones((4,3,2), dtype = 'int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [32]:
# Any other number (making full same)
np.full((2,3),67,dtype = float32)

array([[67., 67., 67.],
       [67., 67., 67.]], dtype=float32)

In [35]:
np.full((2,6),89,int32)

array([[89, 89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89, 89]])

In [9]:
# All other number (full_like)
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [47]:
np.full_like(a,5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [39]:
# Random decimal numbers
import numpy as np
np.random.rand(4,2)

array([[0.47973778, 0.74771118],
       [0.0472816 , 0.83740458],
       [0.24734081, 0.67246686],
       [0.95104532, 0.84144738]])

In [14]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [46]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.56444185, 0.89361451],
       [0.45961309, 0.29546674],
       [0.63863548, 0.68011372],
       [0.49809527, 0.19884749]])

In [45]:
# Random Integer numbers
np.random.randint(3,size = (2,3))

array([[1, 1, 0],
       [0, 2, 0]])

In [51]:
np.random.randint(3,6,size = (3,3))

array([[3, 4, 5],
       [3, 4, 3],
       [3, 4, 4]])

In [52]:
# if you want square like diagonal 1 matrice
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [55]:
# Repeat an array
arr = np.array([{1,2,3}])
r1 = np.repeat(arr,4)
print(r1)

[{1, 2, 3} {1, 2, 3} {1, 2, 3} {1, 2, 3}]


In [67]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,4, axis = 0)
print(r1)


[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [69]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,4, axis = 1)
print(r1)

[[1 1 1 1 2 2 2 2 3 3 3 3]]


In [5]:
import numpy as np
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


*****BE CAREFULL WHEN COPYING ARRAYS!!!


In [6]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
a = np.array([1,2,3])
b = a
b

array([1, 2, 3])

In [9]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [15]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


In [16]:
print(a)

[1 2 3]


********MATHEMATICS


# Mathematics


In [42]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [43]:
a + 2

array([3, 4, 5, 6])

In [44]:
a - 2

array([-1,  0,  1,  2])

In [45]:
a * 2

array([2, 4, 6, 8])

In [46]:

a / 2

array([0.5, 1. , 1.5, 2. ])

In [47]:
a += 2
a

array([3, 4, 5, 6])

In [49]:
a *= 2
a

array([12, 16, 20, 24])

array([5, 6, 7, 8])

array([5, 6, 7, 8])

array([5, 6, 7, 8])

In [53]:

a = np.array([1,2,3,4])
b = np.array([1,0,1,0])
a + b


array([2, 2, 4, 4])

In [51]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [54]:
# Take the sine
np.sin(a)


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [55]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [56]:
np.arcsin(a)

<ipython-input-56-1344fc335193>:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(a)


array([1.57079633,        nan,        nan,        nan])

In [58]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [59]:
####Linear Algebra

#Linear Algebra#


#LINEAR ALGEBRA 

In [64]:
a = np.ones((2,3))
print(a)
b = np.full((3,3),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


array([[6., 6., 6.],
       [6., 6., 6.]])

In [67]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [68]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

#STATISTICS

In [70]:
stats = np.array([[1,2,3],[4,5,6]])
stats


array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
np.min(stats)

1

In [74]:
np.max(stats,axis = 0)

array([4, 5, 6])

In [76]:
np.min(stats,axis = 0)

array([1, 2, 3])

In [77]:
np.min(stats,axis = 1)

array([1, 4])

In [78]:
np.max(stats,axis = 1)

array([3, 6])

In [79]:
np.sum(stats)

21

In [80]:
np.sum(stats,axis = 0)

array([5, 7, 9])

In [81]:
np.sum(stats,axis = 1)

array([ 6, 15])

#Reorganizing Array

# # Reorganizing Arrays

In [84]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [85]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [89]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack((v1,v2,v2,v1,v1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [96]:
# Horizontal stacking vectors
h1 = np.ones((2,4),dtype = 'int32')
h2 = np.zeros((2,2),'int32')
print(h1)
print(h2)
np.hstack((h1,h2))

[[1 1 1 1]
 [1 1 1 1]]
[[0 0]
 [0 0]]


array([[1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0, 0]])

# Miscellaneous
### Load Data from File

In [9]:
import numpy as np
filedata = np.genfromtxt('datafiles.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)


OSError: datafiles.txt not found.

In [8]:
## you can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])